name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # runs at 12AM and 12PM UTC

  workflow_dispatch:  # allows manual trigger

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write  # to push the file
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
